### ISSUE TITLE
[Request] CareKit CocoaPod

### ISSUE THREAD

**Issue by amelnychuck** [carekit-apple/CareKit#1]
Adding CocoaPods as a method for installing the framework would enable seamless version management of the framework in projects already utilizing CocoaPods for dependency management. It also lets a developer import the framework even faster, and better matches the existing ResearchKit project installation options.

ResearchKit can be a dependency, allowing a developer to import both ResearchKit and CareKit pods into his or her project with a single declaration of `CareKit` in the pod file.

**Comment by LeoNatan** [comment]
A better solution is Carthage, not the CocoaPods mess.

**Comment by yuppielabel** [comment]
Since Swift 3 and the package manager is right around the corner, I would not waste time on CocoaPods or Carthage.

**Comment by charlesdavidwince** [comment]
Yes.We can expecting Swift package manager more and Carthage also.Less CocoaPods.

**Comment by istx25** [comment]
Let's compromise and add support for both (CocoaPods and Carthage)!

**Comment by bishalg** [comment]
Its a framework ! and every other frameworks supports CocoaPods and Carthage these days.
So the question is when not which !

**Comment by yuppielabel** [comment]
@bishalg: The future of Carthage and CocoaPods is uncertain. Will there be use for them after the Swift Package Manager? Are there any guarantees they will be around? What happens if they suddenly disappear? As long as you cannot answer these questions, implementing CocoaPod and Carthage is not wise.

If you build a project and depend on fetching code from elsewhere that's not under your own control, you may one day end up opening a big bag of hurt. You should always build your whole app purely from content in your own repositories. Repositories are deleted and accounts are abandoned almost every day,l projects like CocoaPods and Carthage have no guarantee to be around tomorrow. 

An example of dependency injection gone terribly wrong: [How one developer just broke Node, Babel and thousands of projects in 11 lines of JavaScript](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos)

The only other repositories I trust beside my own, are those maintained by Apple. So thats why I strongly suggest not wasting time on something else than Swift Package Manager.

**Comment by a2** [comment]
@yuppielabel I believe the suggestions are to allow for dependency management using CocoaPods or Carthage or Swift Package Manager, but not that any of them should be _required_. I agree with your points that depending on third-party code can be dangerous, but I think you're misunderstanding the recommendation of a CocoaPods podspec or Carthage compatibility as requirements to use either.

**Comment by yuppielabel** [comment]
@a2: I just expressed my opinion why support CocoaPods and Carthage is waste of time since the native Swift Package Manager will be released for regular use together with Swift 3.0. SPM will probably take over for the two others, and since it will work across all platforms, together with the massive support from Apple, the work on the other dependency managers will probably stagnate and be abandoned pretty soon.

**Comment by rajitss** [comment]
We are working on a fix to support CocoaPods for now.

**Comment by bre7** [comment]
CareKit is already compatible with Carthage ;)

**Comment by apbendi** [comment]
Yes, CareKit currently works fine with Carthage. The following is all you need in your `Cartfile:

```
github "ResearchKit/ResearchKit" "stable"
github "carekit-apple/CareKit"
```

**Comment by rajitss** [comment]
CocoaPods support is now live.  
If you run into any problems please open a new issue for it.  Thanks!
