### ISSUE TITLE
How to implement Reminder into CareCard screen of Carekit framwork

### ISSUE THREAD

**Issue by rats083** [carekit-apple/CareKit#159]
Hey Team,

As per my app requierment, I want to implement reminder button on care card row into Carekit demo app and when user click on it, it will open new screen with list of reminders. in that list user can edit / delete reminder. How we achieve it? Any suggestion, most welcome :)

**Comment by ninoguba** [comment]
I've implemented something like this previously and the way I did it I presented a custom task view controller which contains a form step which each question being using a date/time answer format.  You can override the row selection in the care card to display a different view rather than the default care card detail view.
