### ISSUE TITLE
How to take action and disable circle after completion on care card screen.

### ISSUE THREAD

**Issue by rats083** [carekit-apple/CareKit#164]
I want to disable filled circle on carecard and want to perform some action when user tap on unfilled circle and after fill the circle I want to disable it. and should be enable on next day. 
![simulator screen shot may 29 2017 4 09 48 pm](https://cloud.githubusercontent.com/assets/6559961/26546767/47e49050-4489-11e7-8b68-2aa081cf5819.png)
Please let me know how I achieved it into our app.

**Comment by ninoguba** [comment]
Just implement OCKCareCardViewControllerDelegate.didSelectButtonWithInterventionEvent and do a conditional on the event's state property.  If it's already .completed then do nothing (to disable it), otherwise do your action. You should also implement shouldHandleEventCompletionFor and return false.

Hope this helps.

**Comment by rats083** [comment]
thank you @ninoguba
