### ISSUE TITLE
Question: How to create a team care member application ? May i use multiples Care Plan Stores ?

### ISSUE THREAD

**Issue by gustavoserra** [carekit-apple/CareKit#198]
I would like to create one application for doctor sees all your patients and theirs insights. May i use multiples Care Plan Stores ? I can do that ?

**Comment by Pariecemckinney-apple** [comment]
@gustavoserra, Thank you for opening this issue. Please feel free to correct if I'm misunderstanding your question. 

From what I understand, you wish to create a application that patients can download in order to access a care plan that their physician/care team has assigned to them. You also wish to provide a interface for the physician/care team so that they can view the care plan of every patient that they are monitoring. If this is what you are looking for, each patient's device would have one care plan store which would be created from the data that the physician sent from his/her interface. So technically, the physician would be in charge of multiple care plan stores (one per each patient's device), but the interface you create would only send the data to those devices to create a care plan store initially or modify it. No patient should have more than one care plan store. 

This would definitely need a backend service and if you happen to have your own (backend) the latest version of careKit provides hooks to make the process of sending event based data much easier. Also, if you don't have your own backend there are available services that can provide this to you. If you want more information feel free to checkout out our latest WWDC presentation on CareKit where we talk about these features. 

Hope this helps and please feel free to reach back out if you need anything.

**Comment by gustavoserra** [comment]
@Pariecemckinney-apple, thanks for answer my question. You are correct. I saw the 2 videos of WWDC 2017 about news of CareKit and integration with the cloud.

In the last one i saw that the speaker show a physician/care team demo application, but i found only the demo patient application here, then i didn't knew if i could use many stores in a same application.
About the backend, i am doing my own backend because of the law at France, but i saw that we have only one delegate for informe when there is an update at store. It isn't an API like the speaker said.

However, thank you again for your help.

**Comment by Pariecemckinney-apple** [comment]
@gustavoserra, No problem at all. Feel free to reach out anytime. Closing issue now.
