### ISSUE TITLE
CareKit - allow a method to customize the database

### ISSUE THREAD

**Issue by akac** [carekit-apple/CareKit#211]
CareKit's database is okay, but if you want to add your own database you now end up with two databases: one for CareKit and one for your app. This presents issues when you want to do something that brings together a CareKit object and your own. For example - we use groups of activities together and I want to group them together. So I have three choices:

1. Create my own database and my own record that holds references to the CareKit event/activity/results objectIDs. This is problematic for many reasons: its fragile, and the objects are exported as NSObject subclasses, not NSManagedObject subclasses.

2. Edit the CareKit code/database myself to support my additional classes. I don't like that for obvious reasons…

3. Create my own database and save the data I just saved in CareKit again in my database.

**Comment by kelseydedoshka-apple** [comment]
@akac - all 3 approaches you have listed out seem to have pros and cons. I would be interested to know what other kind of data you are storing and some of the requirements on that data as I think that may help me understand your solutions better.

On that note, other data types mixed with CareKit is becoming more common and I would love to understand your use case so we can consider some approaches for this from a  framework perspective as well.

**Comment by erik-apple** [comment]
The recently released CareKit 2.0 addresses this concern.

The new version of the store has a programmatically defined schema that can be extended to store new types. It also allows developers to swap out the CoreData store that we provide with any database of their choice.

If you want some data to live in CareKit's store and other data to live in your own store, you'll still need to grapple with keeping the two in sync. I would recommend either adapting your database to work with CareKit, or extending the CareKit models to contain the extra metadata you need.

CareKit's datatypes all have a `groupIdentifier` tag that you can use for this purpose, so you might be able to use that existing property. If you can't, then you can add new string representable persisted properties like this.

```swift
extension OCKTask {
    var groupName: String? {
        get { userInfo?["groupNameKey"] }
        set {
            userInfo = userInfo ?? [:]
            userInfo["groupKeyname"] = newValue
        }
    }
}
```

**Comment by kutakmir** [comment]
@erik-apple thank you for shedding some light on this very important topic. Can you please elaborate more on the best practices and especially future-proof practices for extending the CareKit?
1) By "can be extended to store new types" do you suggest we override the `makePersistentContainer()` method of `OCKCoreDataStoreProtocol` and modify the `sharedManagedObjectModel`? 
2) For the existing entities, do you mean we should use the `groupIdentifier` string and `userInfo` dictionary to store the extra properties? UserInfo is fine for the storage of extra information, but it would just make it difficult to query as you store the whole structure in a single property. 
3) How would you recommend we go about introducing new relationships?

**Comment by erik-apple** [comment]
All very good questions!

1. The recommended approach is to modify the `sharedManagedObjectModel` used in the body of `makePersistentContainer()` *before* an `OCKStore` is instantiated. The *before* part is very important because of how CoreData treats managed object models. Taking a look at [OCKManagedObjectModel.swift](https://github.com/carekit-apple/CareKit/blob/master/CareKitStore/CareKitStore/CoreData/OCKManagedObjectModel.swift) will give you a pretty good idea of how to add more entities, properties, and even relationships onto the model.

2. Yes, the intended use of `userInfo` is to allow simple extensions of CareKit types without requiring developers to drop down all the way to the managed object model. As you correctly noted though, it is not possible to query based on the contents of `userInfo`, and it doesn't mesh nicely with rich or nested types. It's great for simple metadata additions, like a patient ID number or storing the version of your app that the sample was saved from, but it sounds like it's probably not the tool for what you need to do.

3. See number 1 above.

*Note that the `sharedManagedObjectModel` is not presently exposed through the public API. If you want to modify it today, you'll need to edit the framework itself. We expect to expose it publicly in the future, but we're taking time to make sure we get it right.

**Comment by mef475** [comment]
@erik-apple Thanks for the guidance. Do you have a rough estimate of when you guys plan to expose that functionality in the future?

**Comment by erik-apple** [comment]
Sorry, we don’t have a date yet!

Is there something specific that you’re trying to accomplish presently? Knowing your use case is useful to us as we sculpt the API.

**Comment by mef475** [comment]
@erik-apple We are a startup currently working on our MVP and would love to be able to offer our help with the development effort and spread the word about CareKit's use cases. That's why I was asking about the plans to add customizations, or more broadly about the roadmap. Can we be of help on this (or other) fronts?

**Comment by erik-apple** [comment]
Yes, we'd gladly welcome contributions at all levels! Understanding the use cases and pain points of our developers is valuable for us as we consider how to allot our effort.

We presently have a loosely defined process for defining features for releases. We ask the community to submit feature proposals as issues, which we file under the CareKit Proposals GitHub project. We review those proposals and nominate some of them for the next release, and you can track our progress on implementing them in the corresponding release project. (The CareKit 2.0 release project is already complete, but the next release has not been named yet.)

The low hanging fruit would be to file bugs and open issues about feature requests. No deep technical knowledge required.

If you want to contribute code (and we hope you do!), a great place to start would be by creating new task cards. There are already several task cards that you can use for reference, and the paradigm is well established.

The schema extension API would be a major contribution. If you have ideas about what the required functionality should be, how the public API should be shaped, or how it can be implemented, please share your thoughts with us. I'd encourage you to open an issue or an empty PR in which to discuss your approach before investing time in an implementation.

**Comment by mef475** [comment]
@erik-apple We would definitely like to make contributions. For example, this proposal #355 . Alternatively, I think that other useful tasks that might be added could revolve around follow-ups, reports, etc. I am interested in hearing your guidance. Thanks!
