### ISSUE TITLE
App Crash - PDF Sections 

### ISSUE THREAD

**Issue by smkdoss73** [carekit-apple/CareKit#214]
Step 1: Click Document
Step 2: if click any pdf section means app will crash 

<img width="1440" alt="screen shot 2017-08-24 at 5 43 11 pm" src="https://user-images.githubusercontent.com/7939817/29665954-f6d53b1a-88f3-11e7-8f21-85c0bd8c08cd.png">

# **Mobile Screen**

![simulator screen shot 24-aug-2017 5 43 21 pm](https://user-images.githubusercontent.com/7939817/29665941-ed049612-88f3-11e7-918b-e647d87ddbdc.png)

**Comment by Pariecemckinney-apple** [comment]
@smkdoss73 Thank you for also pointing out this issue. We will begin investigating now and keep you posted.

**Comment by Pariecemckinney-apple** [comment]
@smkdoss73 Thank you again for point out this issue. After investigating we found that the error resides in the "DocumentsTableViewController.swift" file on line 181. 

`webView.load(data, mimeType: "application/pdf", textEncodingName: "", baseURL: URL(string: "")!)`

The problem here is that the baseURL parameter is looking for URL location of the PDF file. However, a empty string is being passed in which is causing the error. To fix the error for now place the below code between 179 and 180. 

![screen shot 2017-09-27 at 11 10 29 am 2](https://user-images.githubusercontent.com/29615893/30929848-9f0138b2-a374-11e7-8400-e908e144c268.png)


After placing this code in the specified areas base the "docURL" variable in baseURL parameter to load the webView.

`webView.load(data, mimeType: "application/pdf", textEncodingName: "", baseURL: docURL! as URL)`

Hope this helps! We will handle fixing the issue in the framework. Closing issue.
