### ISSUE TITLE
carekit.org site frequently unreachable

### ISSUE THREAD

**Issue by gc435** [carekit-apple/CareKit#215]
More often than not, I can't reach http://carekit.org.  Safari, Chrome, and Firefox just say the site is unreachable.  However, Opera sheds some light on the issue and returns a blurb from nginx:

https://twitter.com/jdoe4563/status/906658236316647424

When I can't reach it, I switch over to a VPN from Canada and sometimes I can then get through.  Not always though.

**Comment by nikpocuca** [comment]
I have the same problem, also from Canada.

**Comment by gc435** [comment]
Can someone from Apple please look into this?  I'm trying to connect from a major US medical school, and can't.  I can't build apps with your framework if I can't reach your site.

**Comment by kelseydedoshka-apple** [comment]
@gc435 - we apologize for the issues you have been seeing with the webpage. We have contacted the necessary teams to try and get this resolved so that it is not a reoccurring issue. If you do however run into it again we have been notified that clearing your browser information can sometimes help resolved it.

**Comment by erik-apple** [comment]
We believe this issue has been resolved, as all CareKit information has been migrated to the new https://www.researchandcare.org website.
