### ISSUE TITLE
Daily or Weekly care plan

### ISSUE THREAD

**Issue by raheelsayeed** [carekit-apple/CareKit#223]
I'm wondering if its possible to have Care Card tracking **weekly** instead of Daily.

Is there a good/recommended way to customize frequency of the dates?

**Comment by kelseydedoshka-apple** [comment]
@raheelsayeed - at the moment CareKit only supports a daily calendar, but this is a great suggestion. I am curious how you think this weekly feature might be visualized in the UI?

**Comment by ninoguba** [comment]
Definitely doable through customization.  I did an app where I customized the week view to show the past 7 days (where the right most date is always the current date) instead of the default Sunday to Saturday of the current week.

You can do something similar where your week view shows ordinal (1st, 2nd, ...) numbering for tracking weeks.  The challenge however is at present the CareContents, CareCard, and SymptomTracker views only support showing "day" events.  It could work if you initialize all your care activities to occur only on one specific day of the week (ex. Mondays) and you coincide your week view buttons to query for dates that fall on that day of the week.

**Comment by erik-apple** [comment]
The recently released CareKit 2.0 now supports much more complicated scheduling. See the updated README's section on scheduling for an example of how to create a weekly schedule.

[Scheduling in CareKit 2.0](https://github.com/carekit-apple/CareKit#scheduling)
