### ISSUE TITLE
CareKit+ResearchKit Evolution (like swift-evolution)?

### ISSUE THREAD

**Issue by king7532** [carekit-apple/CareKit#226]
As a company developing a digital health solution, [HealthSteps](http://www.healthsteps.io), partially based on the CareKit + ResearchKit frameworks, I would love to have some process for discussing, reviewing and suggesting changes and enhancements to these frameworks. In much the same way, that the Swift programming language has the [Swift Evolution](https://github.com/apple/swift-evolution) process.

For example, we are developing new features that require us to modify and extend the CareKit data model, with new properties on:
*  [`OCKCarePlanActivity`](/carekit-apple/CareKit/blob/master/CareKit/CarePlan/OCKCarePlanActivity.h)
*  [`OCKCarePlanEvent`](/carekit-apple/CareKit/blob/master/CareKit/CarePlan/OCKCarePlanEvent.h)
*  [`OCKCarePlanSchedule`](/carekit-apple/CareKit/blob/master/CareKit/CarePlan/OCKCareSchedule.h)

I would like to know if other CareKit community members have the same needs, or recommendations and insights on how best to add new properties that could benefit everyone. I would also like to get community feedback and have a discussion on the best way to implement new features and UI/UX, such as monthly recurring activities (taking a medication once a month).

I understand Apple's policy not to disclose any future plans, but that seems to be changing with Apple’s open source commitment to the Swift programming language. This process could be used by the CareKit and ResearchKit open source communities to better coordinate changes and enhancements to the frameworks, that could benefit the community at large.

I am open to any ideas and suggestions to help increase community participation and accelerate open source development of the excellent CareKit and ResearchKit frameworks. Thank you.

**Comment by srinathtm-apple** [comment]
Hey @king7532 , thank you so much for initiating a discussion on this topic. 

We are actively working on resolving some of the issues that you have mentioned above and I would like to take this opportunity to give a sneak peek of some actions we are planning to take to address these concerns -

1) We will soon be expanding write privileges to more members in the ResearchKit/CareKit communities.
2) We are planning to publish a set of guidelines to facilitate discussions amongst developers who are working on adding features to the framework -
- Naming conventions for PRs
- New set of labels, etc
We will be publishing a draft soon to get feedback/reviews from the community.
3) Finally, we receive numerous requests from the medical community regarding features that they would like to see built into the frameworks, our goal is to start listing them out either as PRs or issues so that members in the community who are interested in working on that particular feature can start building them with collaboration from both Apple and other members in the community.

We fully acknowledge that some of these changes have been long overdue, but we cannot emphasize enough as to how excited we are about these upcoming changes.

Please let me know if you have any further thoughts/comments.

**Comment by srinathtm-apple** [comment]
@king7532 - please checkout the new projects tab, specifically this project - https://github.com/carekit-apple/CareKit/projects/2

We wanted use this to keep track of new proposals and also involve the community in influencing the future direction of the CareKit framework. Please let us know what you think about this approach and we would appreciate any feedback or suggestions.

**Comment by king7532** [comment]
@srinathtm-apple I love it, thank you!
