### ISSUE TITLE
Data showing for days older than 14 days are showing on the Care Contents but not showing in Insights even when query is for more than 14 days.

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#249]
The Sample project displays 7 days of data in Insights. Even with a query of more than 14 days, the insights will not show more than 14 days of data. The chart will show more days but the data will be incorrectly "0" even when pain data have been entered for days prior to two weeks. When looping through more than 14 days, the "results.valueString" will be nil.

for offset in 0..<90 {
            // Determine the day to components.
            components.day = offset
            let dayDate = calendar.date(byAdding: components as DateComponents, to: startDate)!
            let dayComponents = calendar.dateComponents([.year, .month, .day, .era], from: dayDate)
            print("dayDate \(dayDate) and dayComponents \(dayComponents)")
            print(backPainEvents[dayComponents].first ?? "-999")
            // Store the pain result for the current day.
            if let result = backPainEvents[dayComponents].first?.result, let score = Int(result.valueString) , score > 0 {
                painValues.append(score)
                painLabels.append(result.valueString)
                print("painLabels.append(result.valueString) \(result.valueString)")
            }

**Comment by akshay-yadav-apple** [comment]
Hey @scdi,
This is an expected behavior for the OCKSample app, since the events query is done on a fixed date range (i.e. 7 days). This issue points out a potential upgrade in the sample app, but unfortunately it is not something in our immediate pipeline. 
Currently, if anybody wants to create 90 days of insight items graph, they would have to update the offset iterator as you did above, update the **components.day to -90 above in the same method**, and update the **calculateQueryDateRange() method in InsightsBuilder** file to return startRange 90 days prior to endDate.

**Comment by scdi** [comment]
Your response was very useful. Thank you.
