### ISSUE TITLE
CareContents Header Calendar - Start from Monday?

### ISSUE THREAD

**Issue by hristiyantrifonov** [carekit-apple/CareKit#255]
Hello!
I can't seem to work out how to make the CareContents Calendar start from Mondays instead of Sundays. What part do I have to change? And is that the only place I have to do the change (i.e will for example the Insights break or continue starting with Sundays).

**Comment by ninoguba** [comment]
I have done a customization like this where instead of showing the default weekday labels, I showed the dates of the past 7 days from the current day.

I had to customize OCKWeekLabelsView.m and modify this part of the code:

```
    if (!_weekLabels) {
        _weekLabels = [NSMutableArray new];
        for (int i = 0; i < 7; i++) {
            UILabel *dayLabel = [UILabel new];
            dayLabel.font = [UIFont systemFontOfSize:12.0 weight:UIFontWeightLight];
            dayLabel.layer.cornerRadius = 5.0;
            dayLabel.clipsToBounds = YES;
            dayLabel.text = _weekStrings[i];
            dayLabel.textAlignment = NSTextAlignmentCenter;
            dayLabel.accessibilityLabel = _axWeekStrings[i];
            [_weekLabels addObject:dayLabel];
        }
    }
```

Once you modify this then you should also make adjustments to your CareContents/CareCard/SymptomsTracker controller, whichever you're using.  If you're using any of these controllers at the same time then there would be more work.

Hope this helps...

**Comment by erik-apple** [comment]
Closing out this issue following the release of CareKit 2.0.

CK 2.0's calendar is localization aware and will automatically use the correct first day of the week based on your device's locale settings.
