### ISSUE TITLE
One doctor many patients

### ISSUE THREAD

**Issue by advatar** [carekit-apple/CareKit#299]
What is the idea for supporting this? There is only one patient per store. While I could create many stores and store the identifiers for (store,patient)  in f.i userData for OCKContact some kind of native support would be nice.

**Comment by erik-apple** [comment]
CareKit is a patient-centric framework and the store is designed to support a single patient with multiple care plans. Our present recommendation is to create a separate store for each patient. Unless you are attempting to aggregate data across patients, which is not something we encourage, then having one store per patient is usually a workable solution. We may consider adding support for multiple patients sometime in the future, but it's not currently on the roadmap. You're welcome to open a proposal for it though, and if enough of the community gets behind it, we might change our mind.

With all that said, there is workaround if you absolutely must have multiple patient per store. We cannot guarantee performance will meet your expectations, and we do not sanction it or support it, but since CareKit is open source there is nothing stopping you from commenting out line 55 of `OCKStore+Patients`.

https://github.com/carekit-apple/CareKit/blob/91210afcde46f94b410f92ea64f5a5119e1e55a2/CareKitStore/CareKitStore/CoreData/OCKStore%2BPatients.swift#L51-L72
