### ISSUE TITLE
CareKit V2 - Adopting SwiftUI and Combine

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#328]
Congratulations on the Version 2 release. I have started migrating my CareKit app to the new version, however...

I notice that there is already a request for samples and additional documentation around ResearchKit integration. I would like to develop my app with a degree of 'future proofing' and would like to adopt both SwiftUI and Combine where that makes sense.

I realise that we are in the early phase of these new technologies but it would help (me) if there could be a version of `OCKSampleApp` that makes "best practice" use of SwiftUI and Combine. I have been trying to read your code and figure out how to

- Catch all the task events for the current day
- Build the equivalent of CareCards and Contacts details (and graphs)
- Build a composite adherence for the day view

I understand I could do the above using with techniques like  `UIViewControllerRepresentable` but a pure Swiftui and Combine design seems to be a better long term architecture.

Could you share some thoughts and guidelines.  Many Thanks  Jonathan

**Comment by gavirawson-apple** [comment]
Hello! We've architected CareKit to fit right in with SwiftUI, so accomplishing those three bullets should be a breeze. You can use our controllers directly and skip the view controllers and `UIViewControllerRepresentable`. The controllers conform to `ObservableObject` and can be used to power a SwiftUI `View`.

> Catch all the task events for the current day

If the goal is to query for all events on the current day, this should do the trick:

```swift
// Create an instance of a controller rather than a view controller.
let controller = OCKSimpleTaskController(storeManager: manager)

// Fetch Doxylamine events for today and set the controller's model. This call will also observe
// changes to the events, and update the controller's model accordingly. 
controller.fetchAndObserveEvents(forTaskID: "doxylamine", eventQuery: .init(for: Date()))
```

You can then use the model that lives on the controller, which will contain all of the events once they are fetched. This of course assumes you have a task in the store with an id of "doxylamine" that has events occurring today.

> Build the equivalent of CareCards and Contacts details (and graphs)

Check out our documentation on building a SwiftUI `View` using our controllers [here](https://github.com/carekit-apple/CareKit#swiftui-). Since our controllers conform to `ObservableObject`, pieces of your view that depend on the controller's model will update when the model changes.

> Build a composite adherence for the day view

I believe the previous explanation fits here too, but if you give a little more detail on what you'd like this to look like we can give some more guidance!

Does that all offer some clarity? Is there anything else I'm missing? As you work more on integrating SwiftUI with CareKit, keep us posted and let us know if there are any pain points!

**Comment by jwaddilove** [comment]
Thank you, I'll digest all of that and try a few bits of refactoring.
