### ISSUE TITLE
OCKSynchronizedStoreManager and SwiftUI

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#331]
Following the response to Issue 328 I’ve started refactoring to use SwitfUI and could use some clarification.

As many Views might need to use the `OCKSynchronizedStoreManager` I assumed that it would make sense to create the StoreManager in `SceneDelegate` thus:

	let store = OCKStore(name: "CareManager", type: .onDisk)
	let storeManager = OCKSynchronizedStoreManager(wrapping: store)

To make the StoreManager available to any view I tried: 

	let contentView = ContentView()
		.environmentObject(storeManager)

Which, unfortunatley fails with: 
	'OCKSynchronizedStoreManager' does not conform to expected type 'ObservableObject'

My second attempted approach was to directly inject the StoreManager into the child views:

	let contentView = ContentView(storeManager: storeManager)

The obvious problem is that I then have to keep onward injecting into dependent views. The second problem is the initialiser sequencing in the child views, if I try something like:
```
 struct DailyView: View {
	var storeManager: OCKSynchronizedStoreManager
	var prednisoloneController = OCKSimpleTaskController(storeManager: storeManager)
	…
```
I get the  “Cannot use instance member 'storeManager' within property initializer; property initializers run before 'self' is available” problem setting up prednisoloneController.

Is it reasonable to want `OCKSynchronizedStoreManager` to be an `ObservableObject`?

Thank you in advance.

**Comment by erik-apple** [comment]
We’re happy to provide clarification!

First things first, you almost certainly do not want to create or keep your store in the scene delegate. If your app supports multiple windows, then a new scene delegate will be instantiated for every window, which means a new store would be created too. You definitely want to share your store across windows, so it should go in the app delegate. I realize you probably put yours in the scene delegate based off our sample app, so we’ll be updating that too to reflect best practices.

Okay, onto the part about making `OCKSynchronizedStoreManager` an `ObservableObject`.

It probably does make sense to provide access to the store manager without having to pass it all the way down one view at a time. What if there is a view in the middle of the tree somewhere that doesn’t even use the store manager? Sure would be a shame to tack an unused property onto that view just so it can pass it to its children!

Making `OCKSynchronizedStoreManager` an `ObservableObject` would allow you to set it as an environment object, but I don’t think that’s really what you want to do. `OCKSynchronizedStoreManager` does not have any meaningful state, and there are no properties on it that you would care to bind to a view, so making it an `ObservableObject` would be a bit misleading. You don’t really care to observe it per se, you just want access to it without having to explicitly pass it around.

I think the solution you’re actually after is creating a new `EnvironmentValue` in the scope of your app. SwiftUI has `EnvironmentValue`s in addition to `EnvironmentObject`s. EVs are similar to EOs, but they don’t need to conform to `ObservableObject`. They’re handy because they aren’t global -- they can be overridden at any node in the view tree.

```swift
struct StoreManagerKey: EnvironmentKey {

    typealias Value = OCKSynchronizedStoreManager

    static var defaultValue: OCKSynchronizedStoreManager = {
        let store = OCKStore(name: "SampleAppStore")
        store.populateSampleData()
        let manager = OCKSynchronizedStoreManager(wrapping: store)
        return manager
    }()
}

extension EnvironmentValues {
    var storeManager: OCKSynchronizedStoreManager {
        get { self[StoreManagerKey.self] }
        set { self[StoreManagerKey.self] = newValue }
    }
}
```

With this code in place, you can write views like this…

```swift
struct CareView: View {
    @Environment(\.storeManager) var storeManager

    var body: some View {
        Text("Your Care View Contents")
    }
}
```
Hope that helps!

**Comment by jwaddilove** [comment]
Erik,

Thank you, that's a great help.

You are absolutely right, I had based the using the scene delegate on the sample, to be honest I'd never even considered multiple window apps.

Your explanation of EVs v. EOs makes a lot of sense and I will adopt that approach. (No need to make `OCKSynchronizedStoreManager` observable).  

It seems that general 'best practise' for Combine and SwiftUI around the internet is still sparse, so thank you again  for taking the time to educate me!

Best wishes
