### ISSUE TITLE
Protection levels in CareKit when installing via Swift Package Manager

### ISSUE THREAD

**Issue by kutakmir** [carekit-apple/CareKit#361]
If you install CareKit via Swift Package Manager then many of the classes and protocols are not accessible because of the internal protection level. For example: OCKContactUpdatable.

Is that intentional?

I would love to use SPM instead of importing the project directly to the codebase.

Can we go over the classes/structs/protocols/... and select which ones to make publicly accessible? I can then update it and make a PR.

**Comment by erik-apple** [comment]
> Is that intentional?

Good question!
Yes, that is intentional! (It should work that way even if you don't use SPM too!)

CareKit exposes a number of `public` and `open` types through its API. Those are the types framework consumers are intended to use. As the framework developers, we make a promise with the community that we will change these methods _as little as possible_.

All of the the other types, the ones marked `internal` or `private`, are implementation details and we reserve the right to change them anytime we want, without any explanation or warning. Preventing framework users from accessing them is Swift's way of guiding developers away from methods that will likely change or disappear in the future.

Having a stable public API is important to developers because it means most changes that we make to the framework will not break their apps. Having internal types is important for us as the maintainers because it means that we have wiggle room to adjust the implementation when we need to add features or fix bugs.

The balance between the public and internal types is important. Too little public surface area means that developers can't do very much. Too much public surface area makes it difficult to make changes. 

Occasionally we'll open up previously internal API's when we feel they won't change anymore or are critical to developers. See #360 for a recent example of that! For the most part though, we've been very intentional about what we have chosen to mark public and what to keep internal, and probably won't make any sweeping changes. `OCKContactUpdatable`, for example, may well disappear in the future, so we wouldn't encourage people to rely on it by making it public.
