### ISSUE TITLE
Issue with OCKSynchronizedStoreManager

### ISSUE THREAD

**Issue by ishanjainofficial** [carekit-apple/CareKit#365]
While using OCKSynchronizedStoreManager (`private extension OCKSynchronizedStoreManager where Store == OCKStore {`), I received the following error:

`Trailing 'where' clause for extension of non-generic type 'OCKSynchronizedStoreManager'`

Despite searching through the documentation, I was not able to find an adequate replacement. Any help would be greatly appreciated!

**Comment by erik-apple** [comment]
In beta versions of CareKit, the synchronized store manager was generic over the store. In the stable version the store is type erased to `OCKAnyStoreProtocol` instead of being a generic parameter on the class.

```swift
// Beta
class OCKSynchronizedStoreManager<Store> { 
    let store: Store
}

// Stable
class OCKSynchronizedStoreManager { 
    let store: OCKAnyStoreProtocol
}
```

Since the store manager is not generic, you don’t need a where clause in extensions anymore.

```swift
extension OCKSynchronizedStoreManager {
    func populateSampleData() {
        let task = OCKTas(...)
        store.addAnyTasks([task], callbackQueue: .main) { result in 
            print(result)
        }
    }
}
```

If you pull the most recent version the samples app, you’ll be able to find lots of up-to-date sample code to guide you!
