### ISSUE TITLE
Updating a task with an outcome

### ISSUE THREAD

**Issue by rutmb** [carekit-apple/CareKit#367]
Hi there,

Can you please explain to me how to update a task with an outcome? If I update the task for the first time the outcome remains there. But the outcome disappears when I update it next time. 

Thanks!

**Comment by erik-apple** [comment]
Can you provide a code snippet to show us what you're doing now? We'll need a bit more context to help you diagnose the problem!

Also, make sure that you've pulled the latest version of CareKit! There were some bug fixes related to this recently.

**Comment by tmbiOS** [comment]
@erik-apple 
We have complex logic for updating tasks and outcomes and I can't reproduce it in the sample app. Our scenario is:
1. We add tasks from the server.
2. We can add the outcome to the tasks.
3. We update the tasks when receiving the push notification.
So we can update the task without outcome (or with the outcome) only once. after that, we get the errors. 
Maybe the problem like this:
You can reproduce it by changing creating `kegelsCard` to this:
```
if let kegelsTask = tasks.last(where: { $0.id == "kegels" }) as? OCKTask {

                var newTask = kegelsTask

                  DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) {
                    newTask.title = "Kegel Exercises \(Date())"
                    self.storeManager.store.updateAnyTask(newTask) { result in
                      print(result)
                    }
                  }

                print("KEGEL TASK: \(kegelsTask)")
                    let kegelsCard = OCKSimpleTaskViewController(task: kegelsTask, eventQuery: .init(for: date),
                                                                 storeManager: self.storeManager)
                    listViewController.appendViewController(kegelsCard, animated: false)
                }
```
So if you run the app 2 times but `kegelsCard` will be with the first title (because there the will be the event assosiated with the first task, not the last with updated title.
```
 open func updateView(_ view: OCKSimpleTaskView, context: OCKSynchronizationContext<OCKTaskEvents?>) {
        view.updateWith(event: context.viewModel?.firstEvent, animated: context.animated)
    }

```

Maybe that's why there is a problem with updating tasks with outcomes. (If we update the task 2 times the outcome checkmark disappears from the UI). We use `OCKChecklistTaskViewController`

**Comment by tmbiOS** [comment]
@erik-apple 
Hi, Erik! Thanks for your latest commit.
I pulled it.
I don't understand how to update tasks with the outcome. (I write `newTask.effectiveDate = Date()`)
If I update and rebuild 2 times the sample app, I get the blank controller with the Kegels task. (maybe it's the bug)

```
if let kegelsTask = tasks.last(where: { $0.id == "kegels" }) as? OCKTask {

                var newTask = kegelsTask

                  DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) {
                    newTask.title = "Kegel Exercises \(Date())"
                    newTask.effectiveDate = Date()
                    self.storeManager.store.updateAnyTask(newTask) { result in
                      print(result)
                    }
                  }

                print("KEGEL TASK: \(kegelsTask)")
                    let kegelsCard = OCKSimpleTaskViewController(task: kegelsTask, eventQuery: .init(for: date),
                                                                 storeManager: self.storeManager)
                    listViewController.appendViewController(kegelsCard, animated: false)
                }

```

<img width="311" alt="screen" src="https://user-images.githubusercontent.com/37933181/75160571-4d481000-572b-11ea-82da-57f745ed8187.png">

**Comment by erik-apple** [comment]
There does seem to be something funny going on here! We'll look into it!

**Comment by erik-apple** [comment]
We've pinned down the underlying issue and are preparing a fix!
