### ISSUE TITLE
Question: Conditional tasks

### ISSUE THREAD

**Issue by ericlewis** [carekit-apple/CareKit#397]
What would be the best way to go about creating tasks which rely on a previous task to have been completed for that day? Such as:

- Took medicine
- Show new tasks in DailyPager

Toggling the specific medicine task should be able to “refresh” the daily list view. 

Is there a way to do this with care plans?

**Comment by ericlewis** [comment]
#375 actually seems like it might be *close* to what I am looking for, not quite the same- but similar.

**Comment by ericlewis** [comment]
Upon looking further: it seems that `OCKDailyTasksPageViewController` is *not* synchronized, so I will take a look in to synchronizing that and attempting to rebuild the list view when the store changes.

**Comment by ericlewis** [comment]
It seems what I am looking for logic wise is something like this:

- daily task for pill
- upon pill being taken for that day- create or update a logging tasks, registering its start for 1hr after the pill was taken up to 24 hours in length.
- if the task already exists, then update it the next day when the pill task is completed again

**Comment by erik-apple** [comment]
Hey Eric, there are a couple different notions of conditional tasks.

1. Tasks that have a fixed schedule, and each event is conditionally shown or not shown based on completion of other task’s events. The key observation is that the task stays the same, but we determine based on the state of the store which events “count”.

2. Tasks whose schedules update dynamically based on the outcomes of other tasks. Here, the task objects actually need to be updated each time dependent data changes. 

The first case is the easier of the two because it doesn’t necessarily require modifying tasks each time an outcome is added. In both cases though, care must be taken to prevent cyclical dependencies between tasks, as these create app crashing infinite loops.

We’ve been considering how we can enable conditional tasks at the framework level, but haven’t arrived at a model that we’re pleased with yet. If you do any work in this space, we’d love to see what you come up with.

It sounds like you’re heading toward the 2nd (harder) variety of conditional tasks, which means you’ll probably need to watch for when outcomes are added/deleted and then update tasks accordingly. 

A good place to clip on would probably be the `OCKSynchronizedStoreManager`’s `notificationPublisher`. You can watch the notifications that get pumped through and respond to the ones that your task is conditional on. In the context of _your specific app_ there may be assumptions you can make that reduce the complexity to something more manageable than trying to solve conditional tasks for _any possible CareKit app_.

**Comment by ericlewis** [comment]
Yes, I am heading more towards the second solution. The first solution seems to me to require some sort of way to have sub tasks at the Store level. Care plans seem to be a way of sort of capturing that, but there is not a way to necessarily nest plans. How to generically tie together a logging event with a medication being taken is an interesting problem still. 

In my case, the second solution also makes sense because I do not show the input until an hour *after* the initial medication event for that day, and the time frame in which the logging is valid is during the time it has taken action. 

So I think what I’ll be going for is some sort of synchronizer that can deal with this logic to update the given task to be valid within a timeframe after the medicine is taken. The task is reused and the medicine only operates for a somewhat specific timeframe, so this seems workable.
