### ISSUE TITLE
Syncing data to the cloud with remoteID

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#416]
Hi,

Is there a recommended way to sync data to the cloud based on `remoteID`. I ask this because the documentation states, `remoteID: A string value that represents a unique identifier, which a remote database uses optionally.`.

What I currently do is after an entity is synced to the cloud, lets say OCKPatient, is take the `objectId` (UUID generated for the cloud object) as the `remoteID` of OCKPatient. Which seems to work fine.

I use `Combine` and `OCKSynchronizedStoreManager` to subscribe to changes like add and updated and attempt to sync to the cloud as recommended by @erik-apple on a previous issue. Of course, there can be issues during a push to the cloud, or no connectivity at all. So whenever there's connectivity available, I would like to search the OCKStore for OCPatient where remoteID == nil. Basically, any entity that hasn't received a remoteID is considered not in the cloud.

1. Is this the intended use of remoteID or at least a good way to use it?
2. If this is a good way, is there a way to fetch `remoteID==nil` (and any other entity that can be nil)? This would be straightforwad if I was using NSPredicate directly to fetch from the OCKStore, but I can't figure out how to do this with the current fetch methods. My current workaround is to fetch all entities, and then filter by remoteID below:

```
fileprivate func synchronizePatients(){
        let query = OCKPatientQuery(for: Date())
        
        storeManager.store.fetchAnyPatients(query: query, callbackQueue: .main){
            result in
            
            switch result{
                
            case .success(let foundPatients):
                
                guard let patients = foundPatients as? [OCKPatient] else{return}
                
                let patientsToSync = patients.filter{$0.remoteID == nil}
                self.addCloudPatients(patientsToSync)
                
            case .failure(let error):
                print("Error in synchronizePatients(). \(error)")
            }
        }
    }
``` 

I haven't ran into an issue with my current way, it just seems like I should be able to query the OCKStore instead of using the filter after getting all entities.

I suppose one way I can get around this is whenever I create a new OCKPatient, set the remoteID to a known string value, like "undefined" or "notInCloud" and then set `query.remoteID = ["notInCloud"]`, then fetch

**Comment by erik-apple** [comment]
Yes, your approach is correct.

Each version of a patient is immutable, so it is sufficient to simply check if that version has been uploaded already or not. Since the patient cannot change without adding a new version, we don't need to consider the update case. Deletes, likewise, are modeled by adding a new version with the `deletedDate` set to a non-nil value.

The intention of the `remoteID` property on `OCKPatientQuery` is to allow you to fetch patients with a particular remoteID, but you've found an important shortcoming -- there doesn't seem to be a way to use it to query patients with no remote ID. Perhaps we should change the query property `remoteID: [String]` to `remoteID: [String?]` to address this problem.

In the meantime, your two workarounds seem reasonable. I would recommend using the "query everything and filter" approach over the "default remoteID" approach. My reasoning is that if you go with the `["notInCloud"]` workaround and ship your app, then later if we change the query to make fetching objects with a nil remoteID work as expected, you'll be stuck supporting the workaround or having to write some kind of migration.
