### ISSUE TITLE
Using Care Kit to take care of someone else?

### ISSUE THREAD

**Issue by Hatsushira** [carekit-apple/CareKit#463]
Dear all,
I'm currently evaluating a use case where I would like to develop an application to keep track of medications, measurements and exercises of someone else and not alone the device owner (actually, for my parents). As I understood, after reading through your documentation here, I cannot add additional patients to the OCKStore after it's initialised and I should use a separate OCKStore for every patient, because all tasks etc. in the OCKStore are linked to this patient.

On the other hand, there are some similarities in the data, f.e. sharing the same general practitioner or other institutions as a contact. I want to avoid that the same information has to be entered twice/several times. So is it possible to manage these in my own Core Data database and just sync them on my own with both OCKStores?

So as a general question: Do you plan to support a use case where you can care for others with Care Kit? Currently, it seems, that the focus is almost only for the device owner. But I'm surely not the first person who thinks about an app of this kind.

Thank you for your great work on Care Kit and I'm looking forward to the additions shown in WWDC20!

Kind regards,
Gerd

**Comment by erik-apple** [comment]
Hi Gerd,

> I cannot add additional patients to the OCKStore after it's initialised and I should use a separate OCKStore for every patient, because all tasks etc. in the OCKStore are linked to this patient.

Yes, that's correct! 

> I want to avoid that the same information has to be entered twice/several times.

I would recommend using ~3 instances of CareKit's store instead of trying to write your own.

Let's say you have a PatientA and a PatientB. Each of them should have their own store.

You can also create a 3rd `OCKStore` that contains only contacts. When you display the `OCKContactsListViewController`, you can instantiate it with the 3rd contact-only store instead of one of the patient's individual stores.

If you have any contacts that _are not_ shared between PatientA and PatientB, you'll need to decide how you want to deal with them. The two basic options are (1) put contacts that are only for PatientA in PatientA's store or (2) put all contacts in the 3rd contact-only store, but use `tags` or `groupIdentifier` to mark the ones that are only for a specific patient.

If you go route (1), you can use the newly introduced `OCKStoreCoordinator` to combine a patient store with the contact only store so that queries return contacts from both. If you go route (2), you can apply filters to your queries to keep only the relevant results.

**Comment by Hatsushira** [comment]
Hi Erik,
thank you for your answer and bringing some light into this.
I will try like you suggested.

**Comment by Hatsushira** [comment]
Dear Erik,
I decided to create an OCKStore for each patient and handle the contacts myself.
Thank you for your assistance.
