### ISSUE TITLE
"completion circles" for the day

### ISSUE THREAD

**Issue by prmehra** [carekit-apple/CareKit#495]
Hi, 

I merged the OCKSample App code (form the carekit repo) into my application and modified the UI elements of it. I used add daily tasks that impacted adherence to my app, however I no longer have any adherence impacting tasks (and I deleted the app from my phone and redownloaded it to ensure the DB didnt have any old data in it). 

Near the top of my screen, my app has the sample weekly view as the sample app has (the days of the week with the circles below them). 

Some circles in the weekly view bar are filled, some are completely empty and some have a dot. Do you know why this may be? Given the current state of my app, the circles should either be always full or always empty.

Note: My eventual goal is to have one task for the user to complete that is adherence impacting. I have a custom swift UI card and when I press the button associated with that card, the task will be considered complete

Thanks so much for your help and responses as usual!

**Comment by erik-apple** [comment]
CareKit's adherence rings have 4 states

```swift
/// `OCKAdherence` specifies how many of their assigned tasks a patient has completed.
public enum OCKAdherence: Equatable {

    /// Indicates that there were no tasks scheduled anytime during the interval in which adherence was computed.
    case noTasks

    /// Indicates that tasks were scheduled, but there were no events suring the interval in which adherence was computed.
    case noEvents

    /// Inidates that events were found, and a fraction of them betwee 0 and 1 was completd.
    case progress(Double)
}
```

Light colored rings that are completely empty indicate that no tasks were scheduled on a date. Typically if you scroll back into the past, to a day before you installed the app, this is what you'll see.

A completely empty ring indicates that you have tasks assigned to you, but there is nothing due on that day. For example, if you have a task that you're supposed to complete once per week on Monday, then the ring for Tuesday will be an empty gray ring indicating that you do have a task, but it's not due today. Days in the future also usually show up as empty rings because you have tasks, but nothing is due yet.

A ring with a dot indicates that you are supposed to do something, but haven't done anything yet. You either forgot to do something on a past day, or you have tasks due today that you haven't gotten to yet.

Does that make sense?

If the rings don't reflect the tasks in your feed, it's probably because there is somewhere else in your app that tasks are being added to the store. If you copied the code from the sample app, check inside of the two `populateSampleData()` methods from AppDelegate.swift to make sure nothing unexpected is being saved.

https://github.com/carekit-apple/CareKit/blob/0cd4e9c0eb3839d4f9ea368c0f12fadd27d51b74/OCKSample/OCKSample/AppDelegate.swift#L47-L48

**Comment by prmehra** [comment]
Hi Erik, thank you for your response and sorry for my late one! Because we had created a custom card associated with one of our tasks, we had to associate an event with the card and fire that accordingly to make sure the task was marked as complete once the user clicked the button at least once. Thanks for your help!

**Comment by erik-apple** [comment]
Glad you got it figured out!
