### ISSUE TITLE
Tracking Blood Pressure in CareKit

### ISSUE THREAD

**Issue by Hatsushira** [carekit-apple/CareKit#509]
Hello,
I'm actually making progress in my project of my family care plan (#463 ) app.

I was able to extend the OCKButtonLogTaskView so that I can capture custom values for any vital signs I want to. For every vital sign I have one task to capture one value.
Now I want to implement a task for recording blood pressure. As we all know this consists of two values. I don't want to have two tasks for capturing these two values.
I could simply store the values as a string 120/80 for example. When I want to show them on a chart I would use an EventAggregator to transform them.

My question is now: Is this the right way to go or should I use f.e. two outcomes one for the upper one for the lower value?

I'm on iPadOS, so no Health App support available for this.

**Comment by erik-apple** [comment]
Yes, blood pressure is tricky.

_This answer is assuming that you don't have access to HealthKit. If you were building for iPhone, I'd nudge you toward taking advantage of HealthKit._

I would recommend creating a single `OCKOutcome` with two `OCKOutcomeValues` attached to it.

```swift
var systolic = OCKOutcomeValue(120)
systolic.kind = "systolic" // Setting the kind is optional, but can be helpful for your own reference

var diastolic = OCKOutcomeValue(80)
diastolic.kind = "diastolic"

var outcome = OCKOutcome(
    taskUUID: bloodPressureTask.uuid!,
    taskOccurrenceIndex: event.scheduleEvent.occurence,
    values: [systolic, diastolic]
)
```

That said, this may not play nicely with the button log view controller, since it assumes one outcome value per entry. You'd need to choose a way to associate the two values with one another so that you can display them in one row and delete them at the same time. You could use the `tags`, `index` or `groupIdentifier` fields for that purpose, but the book keeping will be a bit of pain.

Encoding both values into a single `String` is a bit hackier, but it would also be the least amount of code.

**Comment by Hatsushira** [comment]
Thank you Erik. I went for the one value String approach and it was actually quite easy.

**Comment by erik-apple** [comment]
Great, I'm glad it worked out for you!
