### ISSUE TITLE
How to update values to care store via HealthKit Task? 

### ISSUE THREAD

**Issue by amrutha786** [carekit-apple/CareKit#530]
Currently I am tracking 2 vitals in my App (More vitals to be added) 

I figured out a way to fetch the values from the user (enters manually) & then show the progress in the care store via CareKit Task, 

How do I perform the same via HealthKit task? 

Any code snippet would help.

**Comment by gavirawson-apple** [comment]
Hey @amrutha786! What version of CareKit are you working with?

**Comment by amrutha786** [comment]
Hi @gavirawson-apple.. I am currently working on Carekit 2.1 Version.

**Comment by erik-apple** [comment]
Gavi covers this in detail around 11:52 - 15:22 of our 2020 WWDC presentation, [What's New in CareKit](https://developer.apple.com/videos/play/wwdc2020/10151/).

```swift
// 1. Setting up the Store
import CareKit
import CareKitStore

let coreDataStore = OCKStore(name: "core-data-store")
let healthKitPassthroughStore = OCKHealthKitPassthroughStore(name: "hk-passthrough—store")

let coordinator = OCKStoreCoordinator()
coordinator.attach(store: coreDataStore)
coordinator.attach(eventStore: healthKitPassthroughStore)

let storeManager = OCKSynchronizedStoreManager(wrapping: coordinator)

// 2.Adding HealthKit Linked Tasks to the Store
let schedule = OCKSchedule.dailyAtTime(
    hour: 8,
    minutes: 0, 
    start: Date(),
    end: nil,
    text: nil, 
    duration: .allDay, 
    targetValues: [OCKOutcomeValue(30.0, units: "Minutes")])

let link = OCKHealthKitLinkage(
    quantityIdentifier: .appleExerciseTime, 
    quantityType: .cumulative,
    unit: .minute())

let steps = OCKHealthKitTask(
    id: "exerciseMinutes",
    title: "Exercise Minutes",
    carePlanUUID: nil,
    schedule: schedule,
    healthKitLinkage: link)

storeManager.store.addAnyTask(steps)
```

Once you've added an `OCKHealthKitTask` into the store, you can fetch and display it exactly the same way you would any other task. 

Bear in mind that the common card types like the `OCKSimpleTaskViewController` may not work well with HealthKit tasks because simply checking off the task doesn't provide enough information to create a sample in HealthKit. If you try to display HealthKit driven tasks in a simple task card, then CareKit will generate errors when the user tries to add a new outcome by tapping on the task.

We supply two display-only card styles that work well with HealthKit tasks. (See `NumericProgressTaskView` and `LabeledValueTaskView`). 

If you would like a card that allows the user to input values, such as their temperature or weight, then you'll need to write your own type to collect the value from the user. The README covers how to do this using ResearchKit, but you can modify the example to do it any way you'd like. Once you've collected the value from the user, you can save it into the store. When you save a new outcome to the store, make sure to create the outcome as an `OCKHealthKitOutcome` to ensure that the value makes it into HealthKit.
