### ISSUE TITLE
OCKSchedule Bug Causing Duplicate Tasks/Buttons in OCKGridTaskViewController

### ISSUE THREAD

**Issue by rabdulsal** [carekit-apple/CareKit#560]
Noticed an unusual bug that is reproducible in the Sample App: when creating an OCKSchedule for a OCKTask to be presented in a OCKGridTaskViewController, if the Int '23' is passed as the hour variable for display in the CareCard as a single task at 11:00 PM, two 11 PM tasks and buttons are displayed in the GridTaskView as opposed to the expected single task/button.

Image and code sample provided below. I'm running CareKit via SPM which is pulling from master, so this should represent the latest public code available. Let me know if there's any further information required for investigation.

    // Create Schedule in AppDelegate

    func populateSampleData() {

        let thisMorning = Calendar.current.startOfDay(for: Date())
        let aFewDaysAgo = Calendar.current.date(byAdding: .day, value: -4, to: thisMorning)!
        let beforeBreakfast = Calendar.current.date(byAdding: .hour, value: 8, to: aFewDaysAgo)!

        let schedule = OCKSchedule(composing: [
            OCKSchedule.dailyAtTime(hour: 23, minutes: 0, start: aFewDaysAgo, end: nil, text: nil)
        ])

        // Other configs .....
       
    }

    // Create GridTaskViewController in CareViewController

    override func dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController,
                                          prepare listViewController: OCKListViewController, for date: Date) {

        // Query configs ......

        if let doxylamineTask = tasks.first(where: { $0.id == "doxylamine" }) {
                    let doxylamineCard = OCKGridTaskViewController(task: doxylamineTask, eventQuery: .init(for: date),
                                                                        storeManager: self.storeManager)
                    listViewController.appendViewController(doxylamineCard, animated: false)
                }
  
        // Configure other cards .....

    }

![image](https://user-images.githubusercontent.com/2054819/112249233-c5824d00-8c2d-11eb-811f-d4223554a9e4.png)

**Comment by erik-apple** [comment]
Thanks for reporting this issue! We’ll look into it!

**Comment by erik-apple** [comment]
@rabdulsal Can you confirm that this bug is still present on the `main` branch? We stopped developing on `master` several months ago.

**Comment by gavirawson-apple** [comment]
Thanks for the helpful guidance for reproducing the issue! I was able to see it on my end as well.

It turns out this behavior is expected. The duration of the schedule defaults to one hour - that means that the two events shown are:

1. An event that started last night and ends on the first minute of today (11:00pm yesterday - 12:00am today).
2. An event for tonight (11:00pm tonight - 12:00am tomorrow)

Both events occur in the time window for today, so both will be displayed in the task card. I'm glad you brought up this situation, we can definitely improve the UI here and denote that the first event started yesterday.

If you don't want the event from yesterday to show up on the card, one option is to change the duration to 59 minutes on the schedule when the task is first created.

Let me know if that solves the issue!

**Comment by rabdulsal** [comment]
@erik-apple @gavirawson-apple Adjusting the duration variable did help solve this issue--thanks so much for the update!

**Comment by gavirawson-apple** [comment]
Glad to hear it!
