### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by boisy** [carekit-apple/CareKit#582]
There's a misspelling in the README.md file:

_Download the project source code and drag in CareKit.xcodeproj, CareKitUI.xcodeproj, and **CareKistStore.xcodeproj** as needed. Then, embed the framework as a dynamic framework in your app, by adding it to the Embedded Binaries section of the General pane for your target as shown in the figure below._

That should be CareKitStore.xcodeproj.

**Comment by gavirawson-apple** [comment]
Thanks for the heads up! If you'd like, feel free to submit a Pull Request with the fix!

**Comment by boisy** [comment]
I cloned the repo locally and created a new branch with the fix, but don't have permission to push the branch back up. Do I need to be a member of the repo in order do to this?

**Comment by gavirawson-apple** [comment]
Rather than cloning the repo, you can:

1. Fork the repo.
2. Commit and push the fix to your fork.
3. On the Github page for your fork, you'll see a "contribute" button towards the top. Tapping it will allow you too create a full request into the CareKit repo (See the screenshot below).

<img width="947" alt="Screen Shot 2021-05-18 at 11 01 37 AM" src="https://user-images.githubusercontent.com/51756298/118701577-b7355500-b7c8-11eb-9939-8fee52999f66.png">

**Comment by boisy** [comment]
Thanks! That helped immensely. I just performed the steps.

**Comment by erik-apple** [comment]
This was closed by #583!
Thanks for your contribution!
