### ISSUE TITLE
allow activities to be discontinued

### ISSUE THREAD

**Issue by dukemike** [carekit-apple/CareKit#71]
If an app allows the user to add `OCKCarePlanActivity`, it would be useful to allow the user to discontinue them. The Card View could allow a swipe-left gesture on an activity to allow the user to discontinue the activity immediately, or "tomorrow".

Some thoughts on implementing this:
- we would likely not want activities obtained from an EHR to be deferred by the user. `OCKCarePlanActivity` could have a _canBeDeferred_ flag, which would default to _false_.
- the `OCKCareCardViewControllerDelegate` could be expanded to include a `careCardViewController:canDeferInterventionActivity:` operation which would allow developers to specify whether or not an activity can be deferred, and could be called as `OCKCareCardTableViewCell`s are being created in `OCKCareCareViewController`'s `tableView:cellForRowAtIndexPath`.

@umerkhan-apple: We discussed leveraging `careCardViewController:willDisplayEvents...`, but I don't see how that would be used after looking at the code. I believe we were thinking that the developer would specify which events would be deferrable here.

`OCKCarePlanEvent`s would need similar functionality to allow them be discontinued as well.

**Comment by YuanZhu-apple** [comment]
@dukemike Just want to confirm if `discontinue` means `end` an activity? If so, that's straight forward, just set the end date on the schedule of the activity. 

But deferring an event or events could be much more complex, because it involves the scheduling.
For example,  an weekly repeated schedule, should it be deferred to next day or next week?
And how to track the deferring in the care plan store and so on.

**Comment by YuanZhu-apple** [comment]
Another idea that in my head is to support swipe action menus in the table view of care card or tracker. Basically,  the menu option can be provided by developer through delegate, and the action is up to the developer as well.

**Comment by dukemike** [comment]
Yes, I am proposing that swiping on the row in the card card would cause the activity's end date to be set to _now_ or to tomorrow at 0:00. Deferring an event would have many more edges which I could see as rescheduling. 

Do you think that allowing the developer to specify the menu would be better than adding a '...canDefer...' to supporting ending the activity only?

**Comment by umerkhan-apple** [comment]
@dukemike It was great meeting with you at WWDC. I think this will be a great addition to the Care Card.

We probably don't want to add an extra flag to the activity model. 
This will create data migration issues.

Here's how I think we should proceed for this feature:
1. We should instead add a method to the existing **Care Card Delegate**, something like:
`-(BOOL)careCardViewController:(OCKCareCardViewController *)viewController userCanDiscontinueActivity:(OCKCarePlanActivity *)activity;`
2. Then inside CareCardViewController, we should check the return value for this method and based on it allow the discontinue button to shown on each table view cell (using the table view delegate/data source)
3. By default, the cell will not show the discontinue button.

Let me know what you think! :)

**Comment by dukemike** [comment]
@umerkhan-apple: Do we need _user_ in the method name? Would `canDiscontinueActivity` be sufficient?

Are equivalents for `tableView: willBeginEditingRowAtIndexPath` and `tableView:didEndEditingRowAtIndexPath:` necessary?

**Comment by umerkhan-apple** [comment]
@dukemike We can proceed with `canDiscontinueActivity` and just confirm the name with everyone else during the PR review process. I don't think those tableView equivalents are necessary.

Since the Care Card already has a table view delegate, you would just override the following methods inside `OCKCareCardViewController.h`:

**tableView(_:canEditRowAtIndexPath:)**
- This method will return the value from `canDiscontinueActivity`.

**tableView(_:commitEditingStyle:forRowAtIndexPath:)**
- This method will find the activity at the indexPath and call `setEndDate` with the current date.

**Comment by dukemike** [comment]
pull request #80 opened

**Comment by erik-apple** [comment]
Closing out this issue. The requested feature has been implemented as part of CareKit 2.0
The new `OCKSchedule` struct now has an `end` property that fulfills this requirement.
